name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    # Upload the build output as an artifact (dist directory)
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: ./dist  # Path to your build directory

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    
    # Download the artifact from the previous job
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: build-output  # This must match the artifact name used in the upload step
    
    - run: echo "Setting up NodeJs"
    - name: Setup NodeJs
      uses: actions/setup-node@v4
      with:
        node-version: 12.x

    - run: npm install -g surge
    - run: echo "Deploying website"
    - run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }} 

    - run: echo "Please visit => ${{ secrets.SURGE_DOMAIN }}"
