name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.7]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: rm -rf node_modules package-lock.json
    - run: npm ci
    - run: npm run build
    - run: npm test
    
    # Upload the build output as an artifact (dist directory)
    - uses: actions/upload-artifact@v4
      with:
        name: dist_folder
        path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure deploy job depends on build job
    steps:
    - uses: actions/checkout@v4
    
    # Download the artifact from the previous job
    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: dist_folder  # This must match the name used in the upload step
    
    # Continue deployment steps
    - run: echo "Setting up NodeJs"
    - name: Setup NodeJs
      uses: actions/setup-node@v4
      with:
        node-version: 12.x

    - run: npm install -g surge
    - run: echo "Deploying website"
    - run: surge ./dist ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }} 

    - run: echo "Please visit => ${{ secrets.SURGE_DOMAIN }}"
